# Site settings
title: Oluwaseun Ojeleye
description: About Oluwaseun Ojeleye
#baseurl: "/portfolio" # the subpath of your site, e.g. /blog
#url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Oluwaseun
user_description: My name is Jamiu Oluwaseun Ojeleye. I'm a final year computer engineering student at Karadeniz Technical University, Turkey. I was born and raised in Lagos, Nigeria.
  I am very passionate about programming and engineering as a whole.
  My main research interests lie in the fields of deep learning, image processing, embedded systems and IoT.

user_title: Computer Engineering Student
email: oluwaseunojeleye@pm.me
twitter_username: Jimmystar_17
github_username:  OluwaseunOjeleye
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
