# Site settings
title: Oluwaseun Ojeleye
description: About Oluwaseun Ojeleye
#baseurl: "/portfolio" # the subpath of your site, e.g. /blog
#url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Oluwaseun
user_description: My name is Oluwaseun Ojeleye. I’m a graduate student pursuing an international joint Master's Degree in Imaging and Light in Extended Reality (IMLEX). I was born and raised in Lagos, Nigeria.
  I am very passionate about programming and engineering as a whole.
  My main research interests lie in the fields of image processing, deep learning, computer vision, embedded systems and IoT.

user_title: Computer Engineering Graduate
email: oluwaseunojeleye@pm.me
twitter_username: Jimmystar_17
github_username:  OluwaseunOjeleye

# Google-analytics
google-analytics:
  id: "UA-172746632-1"

exclude: ['package.json', 'src' , 'node_modules']
