# Site settings
title: Oluwaseun Ojeleye
description: About Oluwaseun Ojeleye
#baseurl: "/portfolio" # the subpath of your site, e.g. /blog
#url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Oluwaseun
user_description: My name is Oluwaseun Ojeleye. I hold a Bachelor's degree in Computer Engineering (Turkey) along with three Master's degrees (Finland, France and Japan), all with a profound focus on the captivating realm of Imaging and Light in Extended Reality (IMLEX). I was born and raised in Lagos, Nigeria.
  I am very passionate about programming and engineering as a whole.
  My main research interests lie in the fields of data and image processing, deep learning, computer vision, VR, AR, XR, and embedded systems.

user_title: Computer Engineer
email: oluwaseunojeleye@pm.me
twitter_username: Jimmystar_17
github_username:  OluwaseunOjeleye

# Google-analytics
google-analytics:
  id: "UA-172746632-1"

exclude: ['package.json', 'src' , 'node_modules']
